### ISSUE TITLE
Crashed when switching/loading model

### ISSUE THREAD

**Issue by 1840947815** [shubham0204/SmolChat-Android#92]
There will still be mistakes  by #88 

Thank you so much. Well , I used to modify the source like this, but the app crashed as well.

Therefor, I found that the function for loading model run twice when i click to switch model , and the resource released only one times. Perhaps it is caused by this reason.

After fixing that , it crashed again.
Discovered by accident , I found that the probability of crashing will be greatly reduced when i unchecked `use mmp` and checked `use Mlock` options of chat.

There is still a very small probability to crashed. 
In profilor of Android Studio,  I see it happened when switch from or to a 'big' model just size of 4GB or more, the memory of `other` in android studio increased repadly. But in normal of mode above, the memory of 'other' should be just a few MB. That's a shame , there was none of log for reason.
It crashed at `llama_model_load_from_file()` in LLMInference.cpp of loadModel().

I saw someone said that it is not suggested that to build  llama.cpp's so file. Perhaps this would lose some dependencies in details and lead to errors. I reconstructed the so file according to his suggestions. But it does not work....

Perhaps this would lose some dependencies in details and lead to errors. I reconstructed the so file according to his suggestions.

**Comment by jkkj** [comment]
Hi, this should be solved by my recent PR. There was some invalid state.

**Comment by Jun1orChan** [comment]
Hello, when is it expected to merge PR?

**Comment by shubham0204** [comment]
@Jun1orChan The PR by @jkkj has been merged into the `main` branch and should be available in the next release. The next release should also include #122.

**Comment by Jun1orChan** [comment]
@shubham0204 I'm using the latest main branch code, but the problem remains the same.

**Comment by shubham0204** [comment]
Merged PR #123 to solve this issue.
